import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Evently',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: any) {
  
  return (
    <html lang="en-US">
      <head>
        <title>Evently</title>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat" rel="stylesheet" />
        <link rel='shortcut icon' href='/favicon.ico' />
      </head>
      <body>{children}</body>
    </html>
  )
}